default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: dino
  password: ewedpokp
  host: localhost
  encoding: utf8

development:
  <<: *default
  database: dino_development

test:
  <<: *default
  database: dino_test

production:
  <<: *default
  database: dinnerklub-notifier
